# alorenzetti 202012

# description #####
# this script will parse
# tpms generated by runKallisto
# pipeline

# loading libs ####
source("scripts/loadingLibs.R")

# defining function to compute se
rowSes = function(M){
  M = M %>% as.matrix()
  n = dim(M)[2]
  sds = M %>% rowSds()
  ses = sds / sqrt(n)
  
  return(ses)
}

# reading files ####
# exploratory analysis of kallisto TPM datasets
# to manually compute TPMs, follow the instructions on the following
# page: https://haroldpimentel.wordpress.com/2014/05/08/what-the-fpkm-a-review-rna-seq-expression-units/
# reading and parsing totalrna tpm
totrnatpm=read_delim("data/tableTpmTotalRNA23_v2.tsv",delim="\t")
totrnatpm["mean_abundance_rna_total_TP1"] = totrnatpm %>%
  dplyr::select(matches("total-RNA-[1-3]-1")) %>% rowMeans()
totrnatpm["mean_abundance_rna_total_TP2"] = totrnatpm %>%
  dplyr::select(matches("total-RNA-[1-3]-2")) %>% rowMeans()
totrnatpm["mean_abundance_rna_total_TP3"] = totrnatpm %>%
  dplyr::select(matches("total-RNA-[1-3]-3")) %>% rowMeans()
totrnatpm["mean_abundance_rna_total_TP4"] = totrnatpm %>%
  dplyr::select(matches("total-RNA-[1-3]-4")) %>% rowMeans()

totrnatpm["se_abundance_rna_total_TP1"] = totrnatpm %>%
  dplyr::select(matches("total-RNA-[1-3]-1")) %>% rowSes()
totrnatpm["se_abundance_rna_total_TP2"] = totrnatpm %>%
  dplyr::select(matches("total-RNA-[1-3]-2")) %>% rowSes()
totrnatpm["se_abundance_rna_total_TP3"] = totrnatpm %>%
  dplyr::select(matches("total-RNA-[1-3]-3")) %>% rowSes()
totrnatpm["se_abundance_rna_total_TP4"] = totrnatpm %>%
  dplyr::select(matches("total-RNA-[1-3]-4")) %>% rowSes()

totrnatpm = totrnatpm %>%
  dplyr::select(target_id, contains("abundance")) %>% 
  mutate(locus_tag = sub("\\|.*$", "", target_id)) %>% 
  dplyr::select(-target_id)

# copying pseudoantisense RNA quantification to
# another object and then removing
# them from gene quantification dataset
astotrnatpm = totrnatpm %>%
  filter(str_detect(locus_tag, "pseudoAS$"))

totrnatpm = totrnatpm %>%
  dplyr::filter(str_detect(locus_tag, "pseudoAS$", negate = T))

# adjusting colnames and locus_tags of pseudoantisense dataset
astotrnatpm = astotrnatpm %>% 
  dplyr::rename_with(.cols = contains("rna_total"),
                     .fn = ~ str_replace(.x, "rna_total", "rna_as")) %>% 
  mutate(locus_tag = str_replace(locus_tag, "_pseudoAS", ""))

totrnatpmlong = totrnatpm %>%
  left_join(., astotrnatpm, by = "locus_tag") %>% 
  dplyr::select(locus_tag, contains("mean")) %>% 
  pivot_longer(cols = contains("abundance"),
               names_to = c("measure", "libtype", "timepoint"),
               names_pattern = "^(.*)?_(.*)_(.*)$",
               values_to = "abundance")

# plotting abundance distribution for each timepoint
# ggplot(totrnatpmlong, aes(x=log10(abundance), color = timepoint)) +
#   geom_density() +
#   facet_grid(~ libtype)

# reading and parsing riboseq tpm
ribornatpm=read_delim("data/tableTpmRiboSeqTrim15.tsv",delim="\t")
ribornatpm["mean_abundance_rna_ribofraction_TP1"] = ribornatpm %>%
  dplyr::select(matches("ribosomal_RNA_[1-3]-1")) %>% rowMeans()
ribornatpm["mean_abundance_rna_ribofraction_TP2"] = ribornatpm %>%
  dplyr::select(matches("ribosomal_RNA_[1-3]-2")) %>% rowMeans()
ribornatpm["mean_abundance_rna_ribofraction_TP3"] = ribornatpm %>%
  dplyr::select(matches("ribosomal_RNA_[1-3]-3")) %>% rowMeans()
ribornatpm["mean_abundance_rna_ribofraction_TP4"] = ribornatpm %>%
  dplyr::select(matches("ribosomal_RNA_[1-3]-4")) %>% rowMeans()

ribornatpm["se_abundance_rna_ribofraction_TP1"] = ribornatpm %>%
  dplyr::select(matches("ribosomal_RNA_[1-3]-1")) %>% rowSes()
ribornatpm["se_abundance_rna_ribofraction_TP2"] = ribornatpm %>%
  dplyr::select(matches("ribosomal_RNA_[1-3]-2")) %>% rowSes()
ribornatpm["se_abundance_rna_ribofraction_TP3"] = ribornatpm %>%
  dplyr::select(matches("ribosomal_RNA_[1-3]-3")) %>% rowSes()
ribornatpm["se_abundance_rna_ribofraction_TP4"] = ribornatpm %>%
  dplyr::select(matches("ribosomal_RNA_[1-3]-4")) %>% rowSes()

ribornatpm = ribornatpm %>%
  dplyr::select(target_id, contains("abundance")) %>% 
  mutate(locus_tag = sub("\\|.*$", "", target_id)) %>% 
  dplyr::select(-target_id)

ribornatpmlong = ribornatpm %>%
  dplyr::select(locus_tag, contains("abundance")) %>% 
  pivot_longer(cols = contains("abundance"),
               names_to = c("measure", "timepoint"),
               names_pattern = "^(.*)?_.*_(.*)$",
               values_to = "abundance")

# plotting abundance distribution for each timepoint
# ggplot(ribornatpmlong, aes(x=log10(abundance), color = timepoint)) +
#   geom_density() +
#   facet_grid(~ measure)

# merging totrna, asrna, and riborna tpms
tpm = left_join(totrnatpm, astotrnatpm, by = "locus_tag") %>% 
  relocate(locus_tag)

tpm = left_join(tpm, ribornatpm, by = "locus_tag")
