# alorenzetti 202007

# description ####
# this script will parse proteomics abundance data
# generated by Spectronaut software

# loading libs ####
source("scripts/loadingLibs.R")

# loading files ####
file = "data/Halo_WholeLysate_analysis_HaloIonLibraryVNG_merged_final_2018-04-07_SW100_Protein_Report_20200731.xls"
file2 = "data/Halo_Ribo_analysis_HaloIonLibraryVNG_merged_final_2018-04-07_SW100_Protein_Report.xls"

# they will throw a warning saying
# cols were parsed as.character
# but we ll deal with that later
spectro1 = read_delim(file = file, delim = "\t")
spectro2 = read_delim(file = file2, delim = "\t")

# full join of both dataframes
spectro = full_join(spectro1, spectro2, by = "PG.ProteinAccessions")

# wrangling ####
# adjusting colnames
colnames(spectro)[-1] = sub("^\\[.* ", "", colnames(spectro)[-1])
colnames(spectro)[-1] = sub("^.*_?(BR[1-3])(TP[1-4]).*_.*_.*_(r0[1-3]).*$",
                            "\\2_\\1_\\3",
                            colnames(spectro)[-1],
                            perl = T)
colnames(spectro)[-1] = paste0(c(rep("lysate_", 36),
                               rep("ribo_", 36)),
                               colnames(spectro)[-1])
colnames(spectro)[1] = "locus_tag"

# removing first entry line and pivoting
spectro = spectro[-1, ]

# warnings will be thrown due to
# missing entries ("Filtered" value)
spectro = spectro %>%
  mutate_at(.vars = vars(contains("BR")),
            .funs = as.numeric)

# pivoting data frame
# we will take run means and annotate number of runs used
# I would say using six (of nine) observations is fair enough
spectroLong = spectro %>%
  pivot_longer(cols = contains("BR"),
               names_to = c("libType", "timepoint", "bioRep", "run"),
               names_sep = "_",
               values_to = "abundance") %>% 
  group_by(locus_tag, libType, timepoint) %>% 
  summarise(nruns = 9 - sum(is.na(abundance)),
            mean_abundance = mean(abundance, na.rm = T),
            se_abundance = (sd(abundance, na.rm = T) / sqrt(nruns))) %>% 
  mutate(mean_abundance = case_when(is.nan(mean_abundance) ~ NA_real_,
                                    TRUE ~ as.numeric(mean_abundance)),
         se_abundance = case_when(is.nan(se_abundance) ~ NA_real_,
                                  TRUE ~ as.numeric(se_abundance))) %>% 
  ungroup() %>% 
  filter(nruns >= 6)

# at this moment, I will also remove #####
# protein groups containing more than
# one protein; but I should get back
# to it later to develop an approach that keeps
# only protein groups consisting of repetitions
# peptides shared between distinct protein
# will be ignored in the future
# I was able to identify one of the protein
# groups of one IS type (ISH2)
# and I am keeping it
spectroLong$locus_tag[grepl("VNG0210H", spectroLong$locus_tag)] = "VNG0210H"

spectroLong = spectroLong %>% 
  filter(str_detect(string = locus_tag, pattern = ",", negate = T))

# using longer dataframe, I will
# create a wider version to be able
# to plot heat maps using ComplxHeatmaps
# and furthermore to unify it with
# RNA-Seq data
spectroWide = spectroLong %>% 
  select(-nruns) %>% 
  pivot_wider(names_from = c("libType", "timepoint"),
              names_sep = "_",
              values_from = c("mean_abundance", "se_abundance"))
colnames(spectroWide)[-1] = sub("abundance_", "abundance_protein_", colnames(spectroWide)[-1])

# adjusting locus_tags
# according to dictProd
# "VNG0212H"  "VNG0606G"  "VNG0779C"  "VNG0780H"  "VNG1585Cm"
# don't have a matching sequence in pfeiLocusTag
# those are going to be removed
spectroWide = left_join(spectroWide, dictProd, by = c("locus_tag" = "query_id"))

remove = spectroWide$locus_tag[is.na(spectroWide$subject_id) %>% which()]
spectroWide = spectroWide[!(spectroWide$locus_tag %in% remove),] %>% 
  mutate(locus_tag = subject_id) %>% 
  select(-subject_id, -product.y)

# exploratory plots #####
# plotting densities
# normalization doesnt seem necessary
# distributions are quite similar
# and look like poisson
# ggplot(spectroLong,
#        aes(x = log10(mean_abundance),
#            color = timepoint)) +
#   geom_density() +
#   facet_grid(~libType)

# generating a heat map to check
# sample grouping
# colfunct = circlize::colorRamp2(breaks = c(0,3,6), colors = viridis(3))
# Heatmap(spectro[ ,-1] %>% drop_na() %>% as.matrix() %>% log10(),
#         col = colfunct)
# 
# # timepoint grouping
# Heatmap(spectroWide %>% select(-locus_tag, -contains("se")) %>%
#           drop_na() %>% as.matrix() %>% log10(),
#         col = colfunct)
